on: push
name: CI

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code

    steps:
    # Checkout the code repository first
    - uses: actions/checkout@v2

    # Install Docker and Docker Compose
    - name: Install Docker and Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker --version
        docker-compose --version
    
    # Start the postgres database with docker
    - name: Start the Postgres database with Docker
      run: docker-compose -f docker-compose-db-only.yaml up -d

    # Install dependencies
    - name: Install dependencies
      run: npm install

    - name: run the application
      run: npm run dev

    # Run tests with coverage
    - name: Run tests with coverage
      run: npm run coverage

    # Upload coverage to Codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
