name: Automate Release

on:
  workflow_run:
    workflows: ["CI"]  # Name of the CI workflow (must match the 'name:' field in ci.yaml)
    types:
      - completed
    branches:
      - main  # Only trigger on the main branch
  
  permissions:
    contents: write
    pull-requests: write

  #set the root directory of where the code is
  defaults:
  run:
    working-directory: ./code

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only run if CI succeeded
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run release-please
        uses: googleapis/release-please-action@v4
        with:
          release-type: node                

