name: Automate Release

on:
  workflow_run:
    workflows: ["CI"]  # Must match your CI workflow's name exactly
    types:
      - completed
    branches:
      - main  # Only trigger on `main` branch

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run release-please
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          path: code
          package-name: my-property
