name: Automate Release

on:
  workflow_run:
    workflows: ["CI"]       # Name of the CI workflow (from ci.yaml)
    types:
      - completed

jobs:
  release:
    defaults:
    run:
      working-directory: ./code
    if: ${{ github.event.workflow_run.conclusion == 'success' }} #we only want the release to run if the CI workflow was successful
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: node