name: Automate Release

on:
  workflow_run:
    workflows: ["CI"]  # Must match the name in your ci.yaml
    types:
      - completed
    branches:
      - main  # Only trigger on the main branch

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    working-directory: ./code  # Root directory of your code

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run release-please
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          path: ./code
